name: CI/CD ML - Iris Model via Notebook

on:
  push:
    paths:
      - 'iris.csv' 

jobs:
  train:
    name: Retrain Iris Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute train_model.ipynb --output executed_train_model.ipynb

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-iris-model
          path: model_and_encoder.joblib

      - name: Upload Executed Notebook
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: executed_train_model.ipynb
