name: CI/CD ML - Iris Model via Notebook

on:
  push:
    paths:
      - 'iris.csv' 

jobs:
  train:
    name: Train Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train Model
        run: |
          python train.py

      - name: Verify model exists
        run: |
          test -f model_and_encoder.joblib || (echo "Model not found!" && exit 1)

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model_and_encoder.joblib

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: train

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Trained Model
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: .

      - name: Verify downloaded model
        run: |
          test -f model_and_encoder.joblib || (echo "Model not found after download!" && exit 1)

      - name: Build Docker Image
        run: |
          docker build -t iris-app:latest .

      - name: Save Docker Image to tarball
        run: |
          docker save iris-app:latest -o iris-app.tar

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iris-docker-image
          path: iris-app.tar